les NDArray => Tableaux à N Dimensions

tableau beaucoup plus puissant que les listes classique python / et prennent moins de place en mémoire que data structures (liste / dictionnaires)

In [2]:
import numpy as np

# créer des nd array à 1 dimension => vecteur
# créer des tableau à 2 dimensions => matrice 

tab1 = np.array([ 1,2,3 ])
tab1

array([1, 2, 3])

In [3]:
tab2 = np.array([
    [1,2,3],
    [4,5,6]
])

tab2

array([[1, 2, 3],
       [4, 5, 6]])

matrice => ligne n et colonne m


tab1 = np.array([ 1,2,3 ]) => les dimensions de cette matrice ( n , m ) ( 3, 1 )

In [7]:
tab1.shape

(3,)

In [ ]:
tab1 = tab1.reshape((3,1))     # solution 1 
tab1 = np.reshape( tab1,(3,1)) # solution 2
tab1.shape
# essentiel de donner une valeur pour le nombre de colonne sur les vecteurs

(3, 1)

créer des matrices 2D Numpy : zeros() / full() / ones () / random / eye()

In [11]:
tab3 = np.zeros((2,3))
tab3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
tab4 = np.ones((2,3))
tab4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
tab5 = np.eye(4)
tab5
# matrice carrée avec une diagonale avec que des 1 et les autres valeurs 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
tab6 = np.full((3,4), 6)
tab6

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [ ]:
# pour bloquer la valeur du random => bloque la seed
np.random.seed(0)
# matrice de chiffre aléatoire en 0 et 50
tab7 = np.random.randint(0,50, (3,4))
tab7


array([[44, 47,  0,  3],
       [ 3, 39,  9, 19],
       [21, 36, 23,  6]], dtype=int32)

créer des tableaux à 1D => très pratique pour dessiner matplotlib les valeurs des axes

In [36]:
tab8 = np.arange(0,100, 3)
# 0 min
# 100 max (non inclu)
# 10 pas
tab8

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
tab9 = np.linspace(0,100 , 3)
# 0 min
# 100 max 
# 3 le nombre de valeur que l'on doit avoir dans le 1D Array
tab9


array([  0.,  50., 100.])

Manipulation de matrice

In [39]:
# concaténer des matrices
# horizontalement
tab10 = np.zeros((2,3))
tab11 = np.ones((2 , 4))

tab12 = np.hstack( (tab10 , tab11) )
tab12

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
# vertical
tab13 = np.zeros( (2 , 4))
tab14 = np.ones( (5 ,  4))

# concaténer des matrices
# vertical
tab15 = np.vstack( (tab13 , tab14) )
tab15

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
tab10 = np.zeros( ( 2,3))
tab11 = np.ones( ( 2 , 4))

tab12 = np.concatenate( (tab10, tab11)  , axis=1) # axe des lignes
tab12


array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])

In [52]:
tab13 = np.zeros( ( 5, 4))
tab14 = np.ones( ( 2 , 4))

tab15 = np.concatenate( (tab13, tab14)  , axis=0) # axe des colonnes
tab15

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

exo créer une fonction qui retourne un tableau numpy à 1D

le tableau contient  des  valeurs de 0 à 20 et inverse le signe des nombres de 9 à 15.

[0,1,2,3,4,5,6,7,8, -9, -10, -11 ... -20]

In [ ]:
def gen_1d_array(min , max):
    moitie = (max - min) / 2
    list = []
    i = moitie
    while max + 1 > i:
        list.append( i * -1 )
        i = i + 1
    tab1 = np.arange(min, moitie , 1)
    tab2 = np.array(list)
    return np.hstack((tab1, tab2))

gen_1d_array(0 , 20)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9., -10.,
       -11., -12., -13., -14., -15., -16., -17., -18., -19., -20.])

In [ ]:
# meilleure solution

x = np.arange(21)
print(x)

X = np.arange(21)
X[(x >= 9) & (x <= 15)] *= -1
print(X)

# masking boolean dans les index du tableau numpy


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]
